### ISSUE TITLE
Bugsss...

### ISSUE THREAD

**Issue by QuLogic** [mbonsma/wedding#1]
The pages should work if you add another slash somewhere; either
- `_includes/header.html` add a slash before `blog.html` and `contact.html`
- `_config.yml` add a slash at the end of the basedir (this works in local jekyll too, but you sometimes get double slashs for other places that have it already.)

`contact.html` is not rendering correctly because the yaml front matter is missing. Since it's already a full page, and all you need is the variable substitution, the front matter can be empty (two lines of three dashes.)

Also, `url` in `_config.yml` should be https.

Yes, I'm procrastinating...

**Comment by mbonsma** [comment]
Pretty sure adding a slash in `_includes/header.html` makes the actual site try to go to `mbonsma.github.io/blog`, etc., instead of `mbonsma.github.io/wedding/blog`. Something about a leading slash trying to go to the root? Anyway, I think I'll stick with my decision to ditch the blog and contact pages.

Ahh, the yaml! Great, I was confused why contact wasn't working. Good to know.

**Comment by QuLogic** [comment]
> Pretty sure adding a slash in `_includes/header.html` makes the actual site try to go to `mbonsma.github.io/blog`, etc., instead of `mbonsma.github.io/wedding/blog`.

It's prepended by the `baseurl`, so it becomes `/wedding/blog`, whereas before it became `/weddingblog`.

**Comment by QuLogic** [comment]
Since your wedding's happened already, I guess it's not super important to fix these...

**Comment by mbonsma** [comment]
Lol yeah.
